project_id = "odkwywctpcntgvojnkor"

[functions.ai-insights]
verify_jwt = true

[functions.ai-chat]
verify_jwt = true

[functions.ai-text-correction]
verify_jwt = true

[functions.ai-note-analysis]
verify_jwt = true

[functions.admin-list-users]
verify_jwt = true
